### PR TITLE
added searchmenu plugin

### PR DESCRIPTION
**Pull request by serg-kozhemyakin**

### CODE REVIEW

**Comment by aidanholm** [comment]
Looks good, thanks! For future reference, to squash all commits, you should use an interactive rebase. Then to update the PR, just force push to it (have to force push since squashing changes the PR history)

**Comment by serg-kozhemyakin** [comment]
well, maybe next time i'll try it again :)
meaintime can you tell me briefly -- is it possible to implement next
features with current luakit api -- pinned tabs and tab groups? especially
for someone like me, who doesn't know much about luaking internals and
frankly have not so much spare time.

2017-11-17 9:17 GMT+03:00 Aidan Holm <notifications@github.com>:

**Comment by aidanholm** [comment]
it's possible, but it'd take a bit of work. pinned tabs are already planned and there's an issue open at https://github.com/luakit/luakit/issues/338; not sure about tab groups yet

**Comment by serg-kozhemyakin** [comment]
so as i can understand there's no yet any code for pinned tabs. well, maybe
i'll try to do something if i'll have some time. thx for consultation.
probably will contact you again with more dumb questions about luakit
guts....

2017-11-17 9:43 GMT+03:00 Aidan Holm <notifications@github.com>:

**Comment by aidanholm** [comment]
Sure, you're welcome :) feel free to ask any questions you have

**Pull request merged**
